EventAPP/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos;
using EventLib.model.Account;

namespace EventAPP.Pages.Account
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public LoginInfo? UserInfo { get; set; }
        public void OnGet()
        {
            //this.UserInfo = new LoginInfo { UserName = "admin" };
        }
        public void OnPost()
        {

        }
    }
}

EventAPP/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace EventAPP.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

EventAPP/Pages/EventsPages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class AdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

EventAPP/Pages/EventsPages/Create.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace EventAPP.Pages.EventsPages
{
    public class CreateModel : PageModel
    {
        private IEventRepository _service;
        public CreateModel (IEventRepository service)
        {
            _service = service;
        }
        [BindProperty]
        [Required(ErrorMessage ="Must have an id ")]
        [Range (0,int.MaxValue, ErrorMessage = "Must not be negative")]
        public int Id { get; set; }
        [BindProperty]
        [Required(ErrorMessage ="Missing a name")]
        [StringLength (100,MinimumLength =2,ErrorMessage = "The name must be between 2 and 100 letters")]
        public string Name { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public DateTime Date { get; set; }
        [BindProperty]
        public EventType EventSlags { get; set; }
        public List<EventType> EventsTyper { get; set; }

        public void OnGet()
        {
            EventsTyper = Enum.GetValues<EventType>().ToList();
        }
        public IActionResult OnPost ()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }
            
           
            Events ev = new Events(Id,Name,Description,Date,EventSlags);
            _service.Create(ev);
            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/Delete.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib;
using EventLib.model;

namespace EventAPP.Pages.EventsPages
{
    public class DeleteModel : PageModel
    {
        private IEventRepository _service;

        public DeleteModel(IEventRepository service)
        {
            _service = service; 
        }

        public Events Events { get; set; }
        
        public void OnGet(int id)
        {
            Events = _service.GetById(id);
        }

        public IActionResult OnPostDelete(int id)
        {
            _service.Delete(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostRegret()
        {
            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/Edit.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib;
using EventLib.model;
using System.Diagnostics.Tracing;
using System.ComponentModel.DataAnnotations;

namespace EventAPP.Pages.EventsPages
{
    public class EditModel : PageModel
    {
        private IEventRepository _service;

        public Events Events { get; set; }
        [BindProperty]
        public EventType EventSlags { get; set; }
        public List<EventType> EventsTyper { get; set; }


        public EditModel(IEventRepository service)
        {
            _service = service;
        }


        public void OnGetEnum()
        {
            EventsTyper = Enum.GetValues<EventType>().ToList();
        }

        public IActionResult OnGet(int id)
        {
            Events = _service.GetById(id);
            return Page();

        }
        public IActionResult OnPost(int id, Events events)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _service.Update(id,events);
            return RedirectToPage("Index");
        }

    }
}

EventAPP/Pages/EventsPages/Index.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib.model;

namespace EventAPP.Pages.EventsPages
{
    public class IndexModel : PageModel
    {
        private IEventRepository _service;
        public IndexModel(IEventRepository service)
        {
            _service = service;
        }
        public List<Events> kommendeevents { get; set; }
        public void OnGet()
        {
            kommendeevents = _service.GetAll();
        }
    }
}

EventAPP/Pages/EventsPages/LogIn.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class LogInModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

EventAPP/Pages/EventsPages/LogOut.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class LogOutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

EventAPP/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

EventAPP/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

EventAPP/Pages/Account/Login.cshtml
@page
@model EventAPP.Pages.Account.LoginModel
@{
}

<div class="container border" style="padding:20px">
   <form method="=post">
       <div class="text-danger" asp-validation-summary="ModelOnly"></div>
       <div class="form-group row">
           <div class = "col-2">
                <label asp-for="UserInfo.UserName"></label>
           </div>
            <div class="col-5">
                <input type="text" asp-for="UserInfo.UserName" class="form-control" />                
            </div>
            <span class="text-danger" asp-validation-for="UserInfo.UserName"></span>

       </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="UserInfo.Password"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="UserInfo.Password" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="UserInfo.Password"></span>

        </div>
        <div class="form-group row">
            <div class="col-2">
              <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col-5">
               
            </div>

        </div>
   </form>

</div>

EventAPP/Pages/EventsPages/Admin.cshtml
@page
@model EventAPP.Pages.EventsPages.AdminModel
@{
}

EventAPP/Pages/EventsPages/Create.cshtml
@page
@model EventAPP.Pages.EventsPages.CreateModel
@{
}
<h1> Create a new event  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Id" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Id" class="form-control"/><br>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
                </div>

                <div class="form-group">    
                <label asp-for="@Model.Name" class="control-label">Event name</label><br>
                <input asp-for="@Model.Name" class="form-control" /><br>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                <label asp-for="@Model.Description" class="control-label">Event description</label><br>
                <input asp-for="@Model.Description" class="form-control" /><br>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.EventSlags" class="control-label">Event type</label><br>
                    <select asp-for="EventSlags" class="form-control"><br>
                    @foreach(var eve in Model.EventsTyper)
                    {
                        <option value="@eve">@eve</option>
                    }
                    </select>
                </div><br>

                <div class="form-group">
                <label asp-for="@Model.Date" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Date" class="form-control" /><br>
                <span asp-validation-for="@Model.Date" class="text-danger"></span>
                </div>
                



            <div class="form-group">
                <input type="submit" value="Opret et event" />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/Delete.cshtml
@page
@model EventAPP.Pages.EventsPages.DeleteModel
@{
}
<h1> Delete a event</h1>

<form method="post">
    <div class="form-group">
        <input type="submit"value="Delete event"asp-page-handler="Delete" asp-route-id="@Model.Events.Id"class="btn btn-danger"/>
        <input type="submit" value="Regret" asp-page-handler="Regret" class="btn btn-outline-primary"/>
    </div>
</form>

EventAPP/Pages/EventsPages/Edit.cshtml
@page
@model EventAPP.Pages.EventsPages.EditModel
@{
}
<h1> Update a Event  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Events.Id" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Events.Id" class="form-control" /><br>
                <span asp-validation-for="@Model.Events.Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Events.Name" class="control-label">Event name</label><br>
                <input asp-for="@Model.Events.Name" class="form-control" /><br>
                <span asp-validation-for="@Model.Events.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Events.Description" class="control-label">Event description</label><br>
                <input asp-for="@Model.Events.Description" class="form-control" /><br>
                <span asp-validation-for="@Model.Events.Description" class="text-danger"></span>
            </div>
@*
            <div class="form-group">
                <label asp-for="@Model.EventSlags" class="control-label">Event type</label><br>
                <select asp-for="EventSlags" class="form-control">
                    <br>
                    @foreach (var eve in Model.EventsTyper)
                    {
                        <option value="@eve">@eve</option>
                    }
                </select>
            </div><br>*@

            <div class="form-group">
                <label asp-for="@Model.Events.Date" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Events.Date" class="form-control" /><br>
                <span asp-validation-for="@Model.Events.Date" class="text-danger"></span>
            </div>




            <div class="form-group">
                <input type="submit" value="Save" class. />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/Index.cshtml
@page
@using EventLib.model;
@model EventAPP.Pages.EventsPages.IndexModel
@{
    ViewData["Title"] = "Events";
}

<h1>Oversigt over kommende events</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Event type</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var e in @Model.kommendeevents)
        {
        
          <tr>
                    <td>
                        @e.Id
                    </td>
                    <td>
                        @e.Name
                    </td>
                    <td>
                        @e.Description
                    </td>
                    <td>
                        @e.EventSlags
                    </td>
                    <td>
                        @e.Date
                    </td>
                    <td>
                        <a asp-page="Delete" asp-route-id="@e.Id">Delete</a> | <a asp-page="Edit" asp-route-id="@e.Id">Edit</a>
                    </td>
          </tr>
   
        }
    </tbody>
</table>

<p>
    <a asp-page="Create">Opret et event</a>
</p>

EventAPP/Pages/EventsPages/LogIn.cshtml
@page
@model EventAPP.Pages.EventsPages.LogInModel
@{
}

EventAPP/Pages/EventsPages/LogOut.cshtml
@page
@model EventAPP.Pages.EventsPages.LogOutModel
@{
}

EventAPP/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EventAPP/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">EventAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="EventsPages/Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EventAPP - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>